spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skb_bazar
    username: postgres
    password: postgreSql123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
